/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("com.gradleup.shadow") version "9.4.1"
}

dependencies {
    implementation("io.javalin:javalin:7.1.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0")
    implementation("org.slf4j:slf4j-simple:2.0.17")
    implementation("org.apache.commons:commons-text")
    implementation(project(":client"))
    implementation(project(":ddb"))
    implementation(platform("software.amazon.awssdk:bom:2.42.28"))
    implementation("software.amazon.awssdk:dynamodb")
    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
    implementation("com.google.dagger:dagger:2.52")
    annotationProcessor("com.google.dagger:dagger-compiler:2.52")
}

application {
    // Define the main class for the application.
    mainClass = "com.turntable.app.App"
}
