/*
 * This source file was generated by the Gradle 'init' task
 */
package com.turntable.app;

import com.turntable.list.LinkedList;

import static com.turntable.utilities.StringUtils.join;
import static com.turntable.utilities.StringUtils.split;
import static com.turntable.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
