/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

tasks.javadoc {
    options {
        (this as StandardJavadocDocletOptions).apply {
            addBooleanOption("html5", true)
            encoding = "UTF-8"
            addBooleanOption("Xdoclint:missing", true)
            // addBooleanOption("Werror", true)
        }
    }
}

tasks.build {
    dependsOn(tasks.javadoc)
}
